set(Wire_RECURSE True)
set(Ethernet_RECURSE True)
set(SD_RECURSE True)
set(WiFi101_RECURSE True)
set(enhanced-io_RECURSE True)
set(lwstreams_RECURSE True)
set(phylum_RECURSE True)
set(I2S_RECURSE True)
